### PR TITLE
New scripts and experiment templates with examples

### PR DESCRIPTION
**Pull request by JamesOwers**
This is quite a big PR but could do with a review, at least for the changes to the scripts. It also removes old gridengine scripts

# 1. Script changes

## New scripts
* `myjobs` - simple shortcut for `squeue -u $USER`
* `sinline` - allows for running inline commands on a specified node. Similar to `onallnodes` except you dont need to create a script file

## Changes
* `killmyjobs` - fixed an edge case
* `interactive` & `interactive_gpu` - split into two commands, and made work on arbitrary clusters

## Removals
I'm voting to remove all the badboys in ./gridengine for now - they'll always be
accessible in the git history, but for now, they add confusion for
a new user.

# 2. Experiment templates and examples
I put forward a framework for performing experiments for people to build upon. Not completely finished but the template is there, the command `run_experiment` is well used, and there is a minimal working example for users to learn a slurm cluster works.

If you would like to review, the quickest thing to do is try to complete the 10 minute exercise outlined in [`experiments/examples/simple/README.md`](https://github.com/JamesOwers/cluster-scripts/tree/slurm_templates/experiments/examples/simple)

# TODO:
* ~Update documentation - esp root level~
* ~Complete MNIST example [`experiments/examples/mnist/README.md`](https://github.com/JamesOwers/cluster-scripts/tree/slurm_templates/experiments/examples/mnist)~

### CODE REVIEW

**Comment by RyanrDavies** [comment]
Had a quick look at the code, will play around with it more tomorrow.
Few comments:
- `killmyjobs`, `interactive`, `interactive_gpu` all look fine to me.
- Not sure what `sinline {options} {command}` adds compared to `srun {options} {command}`?
- `myjobs` could be set up as a bash alias, which the user would source in their `.bashrc`. Doesn't make much difference at the moment, but if additional shortcuts are added the alias approach would be preferred as they could all be defined in one file.

The example experiment setup looks impressive!

**Comment by JamesOwers** [comment]
@RyanrDavies - you're a diamond. You supposed to be resting 👀 ! ❤️ 

> * Not sure what `sinline {options} {command}` adds compared to `srun {options} {command}`?

Well...now neither am I. I didn't actually know this was essentially how srun behaved 😂 ! However, I'm struggling a bit getting srun to run commands (as opposed to a bash script). For example, I can get it to run ls, but echo an environment variable:
```
$ srun --partition=PGR-Standard -w damnii03 'ls'
> cluster-status
> down-gpus
> ...
>whoson

$ srun --partition=PGR-Standard -w damnii03 'ls; echo hi'
> slurmstepd: error: execve(): ls; echo hi: No such file or directory
> srun: error: damnii03: task 0: Exited with exit code 2

$ srun --partition=PGR-Standard -w damnii03 'echo $SLURMD_NODENAME'
> slurmstepd: error: execve(): echo $SLURMD_NODENAME: No such file or directory
> srun: error: damnii03: task 0: Exited with exit code 2

$ sinline -n damnii03 -c 'echo $SLURMD_NODENAME' -s '--partition=PGR-Standard'
> Submitted batch job 665957
> damnii03
```
It looks to me like srun is always expecting a file or executable, not a nice string you can simply run. I feel like I'm definitely wrong! But in the unlikely event I'm correct, I'll change the sbatch to srun in sinline so as not to require the log files.

> * `myjobs` could be set up as a bash alias, which the user would source in their `.bashrc`. 

Doesn't make much difference at the moment, but if additional shortcuts are added the alias approach would be preferred as they could all be defined in one file.
Yeah, I mean, given we're putting these commands on the $PATH it doesn't make an awful lot of difference for most users. `cluster-status` is much the same really. For now, I'm fine piling these all in as 'executables', but if we define loads of shorties, maybe grouping them together and simply getting users to add to .bashrc would make sense? For now, for clarity (easy to document), and usability, I reckon we should keep as is.

> The example experiment setup looks impressive!

Thanks man. It's taken a few days. Idea for `examples/simple` is zero setup required: people could turn up to a <1 hour seminar and get an intro to slurm with no prep by just running through that exercise (I hope!).

`examples/mnist` will be a full intro to running experiments with conda and pytorch

**Comment by JamesOwers** [comment]
Ok, the MNIST example is now complete. Give it a whirl.

**Comment by RyanrDavies** [comment]
> It looks to me like srun is always expecting a file or executable, not a nice string you can simply run.

I think that it will work if you don't quote the string:
`srun --partition=PGR-Standard -w damnii03 echo $SLURMD_NODENAME`
Though I've not had a chance to check that, and I guess that still wouldn't work for chaining commands with `;`.

**Comment by JamesOwers** [comment]
@RyanrDavies In summary of `srun` stuff for inline:
* Looking at [docs for `srun`](https://slurm.schedmd.com/srun.html), it expects an executable, so wont do what I want
* [`sbatch`](https://slurm.schedmd.com/sbatch.html) has an option --wrap, this **does** do what I want (takes a string and just runs it), *except* it **doesn't** just spit logs to terminal

So `sinline` has a place. I'm going to leave the script as it - it's nice to have the -k option for debugging.

If it's ok with you, I'm going to merge this in now as I need it on the main branch for tomorrow!

**Pull request merged**
